// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRoAs5cL-kkdvt0zhn975njgaSobRwEE',
    appId: '1:443239791000:web:238fa6cdc8024c0da453ed',
    messagingSenderId: '443239791000',
    projectId: 'myapp-b1e3d',
    authDomain: 'myapp-b1e3d.firebaseapp.com',
    storageBucket: 'myapp-b1e3d.firebasestorage.app',
    measurementId: 'G-50YMW6W57P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNWsdxWuoEx69K8u3lCuTp_Y4hj9HNwA',
    appId: '1:443239791000:android:6a1c1e95258c1cffa453ed',
    messagingSenderId: '443239791000',
    projectId: 'myapp-b1e3d',
    storageBucket: 'myapp-b1e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcftDeD3tW63ck1RajUvKCBH7wnxr5YWk',
    appId: '1:443239791000:ios:89193d31a6d36b31a453ed',
    messagingSenderId: '443239791000',
    projectId: 'myapp-b1e3d',
    storageBucket: 'myapp-b1e3d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcftDeD3tW63ck1RajUvKCBH7wnxr5YWk',
    appId: '1:443239791000:ios:89193d31a6d36b31a453ed',
    messagingSenderId: '443239791000',
    projectId: 'myapp-b1e3d',
    storageBucket: 'myapp-b1e3d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeRoAs5cL-kkdvt0zhn975njgaSobRwEE',
    appId: '1:443239791000:web:bf7823a49fe46839a453ed',
    messagingSenderId: '443239791000',
    projectId: 'myapp-b1e3d',
    authDomain: 'myapp-b1e3d.firebaseapp.com',
    storageBucket: 'myapp-b1e3d.firebasestorage.app',
    measurementId: 'G-XDEBQ58F4S',
  );

}